---
version: 2
multi-ecosystem-groups:
  deps:
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "feat:"

updates:
  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "deps"
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "pip"
    directory: "/build"
    patterns:
      - "*"
    multi-ecosystem-group: "deps"
    ignore:
      - dependency-name: "cython"
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-patch"
