# Hadolint configuration for super-linter
# Ignore rules that are not applicable or too strict for this project
ignored:
  # DL3018 - Pin versions in apk add
  - DL3018
  # DL3013 - Pin versions in pip
  - DL3013
  # DL3042 - Avoid use of cache directory with pip
  - DL3042
